services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Port for AMQP protocol
      - "15672:15672"  # Port for management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
